apiVersion: v1
kind: Service
metadata:
  name: practica-eks-service-2
  labels:
    name: practica-eks-deploy
    app: practica-eks-app
spec:
  type: NodePort
  selector:
    app: practica-eks-app
  ports:
    - protocol: TCP
      port: 4500
      nodePort: 30127



    